name: Publish Master Snapshot

on:
  push:
    paths:
      - '**/java/**'
      - '*.java'
      - '*.gradle'
      - '*.properties'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java Publish Master Snapshot

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Code Style
        run: ./gradlew spotlessCheck

      - name: Build
        run: ./gradlew classes

      - name: Test
        run: ./gradlew test jacocoTestReport testCodeCoverageReport

      - name: SonarQube
        run: ./gradlew sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Cleanup Previous Snapshots
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'testcontainers-extensions'
          package-type: 'maven'
          ignore-versions: '^\\d+\\.\\d+\\.\\d+$'

      - name: Publish Snapshot
        run: ./gradlew publish closeAndReleaseStagingRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
          OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.OSS_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.OSS_SIGNING_PASSWORD }}
